title: Shelton D. Taylor
description: Theology Writer
description: MA Theological Studies @LibertyU
description: Essays on union with Christ, the kingdom of God, and faith as allegiance to the risen King.
permalink: /:title/
